spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/ncov?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
